// types/product.ts

// Define a Product interface based on your database columns
export interface Product {
  sku: string;
  family: string;
  products_available_to_serve: string;
  shipping_dimensions: string;
  case_dimensions_in: string;
  product_length_in: number;
  product_weight_lbs: number;
  list_price: number;
  map_price: number;
  upc: string;
  hts_code: string;
  flow_rate_gpm: number;
  pallet_quantity: number;
  case_quantity: number;
  case_price: number;
  case_weight_lbs: number;
  number_of_taps: number;
  glycol_lines: number;
  ice_capacity_lbs: number;
  btuhr_k: number;
  interior_diameter_in: number;
  shipping_weight_lbs: number;
  working_height_in: number;
  trunk_line_length_in: number;
  height_of_ceiling_in: number;
  diameter_in: number;
  caster_quantity: number;
  mug_capacity: number;
  wheel_diameter_in: number;
  spray_head_flow_rate_gpm: number;
  hose_length_in: number;
  hose_length_ft: number;
  gallon_capacity: number;
  beverage_line_diameter_in: number;
  chase_diameter_in: number;
  glycol_line_diameter_in: number;
  hertz_hz: number;
  massachusetts_listed_certification: boolean;
  cec_listed_certification: boolean;
  ada_compliance: boolean;
  freight_class: string;
  country_of_origin: string;
  production_code: string;
  product_status: string;
  compressor_location: string;
  top_finish_options: string;
  cold_plate: string;
  handle_type: string;
  spout_style: string;
  brakes: string;
  inlet: string;
  bottle_capacity: string;
  refrigerant: string;
  spout_size_in: number;
  thread: string;
  pumps: string;
  gas_system_compatibility: string;
  wrap_style: string;
  restock_fee: string;
  din_cables: string;
  spray_head_pattern: string;
  type: string;
  heat_recovery: string;
  stream_type: string;
  cabinet_side_finish: string;
  front_finish: string;
  division: string;
  visibility: string;
  nsf_certification: string;
  csa_certification: string;
  ul_certification: string;
  etl_certification: string;
  asse_certification: string;
  iampo_certification: string;
  series: string;
  warranty: string;
  doordrawer_finish_options: string;
  mounting_style: string;
  tower_style: string;
  underbar_structure_options: string;
  bowl_location: string;
  centers: string;
  doordrawer_style: string;
  drain_size: string;
  outlet: string;
  beverage_compatibility_options: string;
  tower_location: string;
  tower_finish: string;
  hp: string;
  tower_mounting: string;
  ice_bin_location: string;
  power_source: string;
  voltage: string;
  drain_location: string;
  psi_range: string;
  valve_type: string;
  plug_type: string;
  collaboration: string;
  product_height_in: number;
  features: string;
  product_description: string;
  erp_description: string;
  materials: string;
  finish: string;
  product_depth_in: number;
  operating_range: string;
  raises_equipment: string;
  temperature_range: string;
  aq_description: string;
  design_upgrades: string;
  faqs: string;
  issuessolutions: string;
  upsell_items: string;
  parent_products: string;
  parts_and_accessories: string;
  beverage_lines: string;
  images: string | null;
  videos: string | null;
  spec_sheet: string | null;
  manuals: string | null;
  sell_sheet: string | null;
  brochure: string | null;
  backsplash_height_in: number | null;
  bowl_size_in: string | null;
  perforated_inserts: string | null;
  related_products: string | null;
  includes: string | null;
  amps: string | null;
  compressor_size_in: string | null;
  phase: string | null;
  partsbykrowne: string | null;
  load_capacity_lbs_per_caster: string | null;
  plate_size_in: string | null;
  caster_overall_height_in: string | null;
  keg_capacity: string | null;
  product_weight: string | null;
  drain_outlet: string | null;
  product_width_in: number | null;
  california_prop_warning: string | null;
  website_link: string | null;
  product_height_without_legs_in: string | null;
  internal_only_product: string | null;
  coo: string | null;
  tags: string | null;
}